# Generated by Django 2.2.3 on 2019-10-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='face',
            field=models.CharField(default='/myadmin/static/img/assets/img/user06.png', max_length=100),
        ),
    ]
