# Generated by Django 2.2.3 on 2019-10-18 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20191017_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
