# Generated by Django 2.2.3 on 2019-10-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_users_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='face',
            field=models.CharField(default='/static/myadmin/assets/img/user06.png', max_length=100),
        ),
    ]
