# Generated by Django 2.2.3 on 2019-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20191018_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='usertype',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
