# Generated by Django 2.2.3 on 2019-10-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_auto_20191018_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
