# Generated by Django 2.2.3 on 2019-10-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myadmin', '0008_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catename', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('face', models.CharField(default='/static/myadmin/assets/img/user06.png', max_length=100)),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('homeaddress', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('usertype', models.CharField(max_length=1, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('isdelete', models.BooleanField()),
            ],
        ),
    ]
