# Generated by Django 2.2.3 on 2019-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_booktype_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='isdelete',
        ),
        migrations.AddField(
            model_name='users',
            name='isdel',
            field=models.CharField(default='004001', max_length=10),
        ),
    ]
