# Generated by Django 2.2.3 on 2019-10-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_auto_20191018_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booktype',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
