# Generated by Django 2.2.3 on 2019-10-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_books_booktype_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Booktype',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
