# Generated by Django 2.2.3 on 2019-10-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_bookimgs_books_booktype_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('select', models.IntegerField(default=0)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
    ]
