# Generated by Django 2.2.3 on 2019-10-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('user_address', models.CharField(max_length=200)),
                ('isdefault', models.CharField(default=0, max_length=1)),
                ('isdel', models.CharField(default=0, max_length=1)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
    ]
