# Generated by Django 2.2.3 on 2019-10-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': (('show_Books', '查看图书列表'), ('create_Books', '添加图书'), ('edit_Books', '修改图书'), ('delete_Books', '删除图书'))},
        ),
        migrations.AlterModelOptions(
            name='booktype',
            options={'permissions': (('show_Booktype', '查看图书分类列表'), ('create_Booktype', '添加图书分类'), ('edit_Booktype', '修改图书分类'), ('delete_Booktype', '删除图书分类'))},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('show_Order', '查看订单列表'), ('create_Order', '添加订单'), ('edit_Order', '修改订单'), ('delete_Order', '删除订单'))},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('show_Users', '查看用户列表'), ('create_Users', '添加用户'), ('edit_Users', '修改用户'), ('delete_Users', '删除用户'))},
        ),
    ]
